image: golang:1.21

stages:
    - preparation
    - test

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

preparation:script:
  - go version
  - docker --version

test:golangci-lint:
    stage: test
    image: golangci/golangci-lint:v1.54.2
    script:
        - golangci-lint run -v $(go list ./... | grep -v /pkg/)

test:unit_tests:
    stage: test
    script:
        - go test -v -race -covermode atomic -coverprofile=coverage.txt ./internal/...
    artifacts:
    paths:
        - coverage.txt
    tags:
        - docker
