version: '3'
services:

  app:
    build: .
    ports:
    - "8080:8080"
    depends_on:
    - nats
    - postgres
    environment:
      CONFIG_PATH: /config/develop.yaml
      DB_PATH: /config/db/postgres.yaml
      DOCKER_PATH: /config/docker.yaml

  postgres:
    environment:
      POSTGRES_DB: notify
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      interval: 10s
      retries: 5
      start_period: 10s
      test:
      - CMD-SHELL
      - pg_isready -U postgres -d notify
      timeout: 5s
    image: postgres:14.9
    ports:
      - 5433:5432
    volumes:
    - pg-data:/var/lib/postgresql/data
  
  nats:
    image: nats:2.10
    ports:
      - "4222:4222"

  nats-streaming:
    image: nats-streaming:0.25
    ports:
      - "8222:8222"
    depends_on:
      - nats

  integration:
    build:
      context: .
      dockerfile: tests/integration/Dockerfile
    container_name: integration
    image: integration
    depends_on:
      - app

volumes:
  pg-data: