env: develop
Addr: "127.0.0.1:8080"
logger:
  logfile: "/artifacts/service_log.log"
  levelInfo: "debug"

nats:
  host: "localhost:4222"
  subjects: [
    "mailing.general",
    "mailing.additional"
  ]